esphome:
  name: pet_feeder
  platform: ESP8266
  board: d1_mini
  includes:
    - src/PetFeederComponent.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pet Feeder Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 490 Hz # Like arduino nano
    inverted: false
    id: driver_pwm_output
  - platform: gpio
    pin: D2
    id: driver_direction_output
  - platform: gpio
    pin: D5
    id: driver_speed_power
  # - platform: gpio
  #   pin: D6
  #   id: pulse_counter

sensor:
  - platform: pulse_counter
    pin: D6
    update_interval: 100ms
    id: driver_speed_counter
    name: "Pulse Counter"

custom_component:
- lambda: |-
    auto controller = new SimpleFeederController(driver_pwm_output, driver_direction_output);
    auto watchdog = new Watchdog(driver_speed_power, driver_speed_counter, controller);
    App.register_component(watchdog);
    auto feeder_component = new PetFeederComponent(watchdog, controller);
    return {feeder_component};
